### ISSUE TITLE
Link quebrado

### ISSUE THREAD

**Issue by pertusatti22** [CharlestonRibeiro/Architectural_Studies#1]
No Arquivo README.md o link para Imports em Decisões Básicas está 404 not found.

link com erro: https://github.com/CharlestonRibeiro/Architectural_Studies/blob/main/basic/Imports.md 
link correto: https://github.com/CharlestonRibeiro/Architectural_Studies/blob/main/basic/imports.md

**Comment by CharlestonRibeiro** [comment]
Obrigado @pertusatti22 por avisar, foi resolvido.
